version: "3.4"

services:
  api:
    build:
      target: dev
    command: yarn dev
    ports:
      - 3200:3000
      - 3201:9229
    volumes:
      - .:/app:cached

  ui:
    build:
      target: dev
    command: yarn dev
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
